/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleNavigation: typeof import('./components/structural/ArticleNavigation.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    LeftArrow: typeof import('./components/icons/LeftArrow.vue')['default']
    Markdown: typeof import('./components/structural/Markdown.vue')['default']
    PopoverNavigation: typeof import('./components/structural/PopoverNavigation.vue')['default']
    PostList: typeof import('./components/structural/PostList.vue')['default']
    RightArrow: typeof import('./components/icons/RightArrow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNavigation: typeof import('./components/structural/SideNavigation.vue')['default']
    SiteHeader: typeof import('./components/structural/SiteHeader.vue')['default']
  }
}
